id = "andromeda"
name = "Andromeda"
schema_version = 1
version = "0.1.1"
authors = ["ChocolateNao <andrey12q11@gmail.com>"]
description = "ðŸŒ’ A popular VScode theme brought to Zed"
repository = "https://github.com/ChocolateNao/andromeda-zed"
